# Generated by Django 3.0.8 on 2020-07-18 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='firstname',
            field=models.CharField(default='', max_length=70),
        ),
        migrations.AddField(
            model_name='employee',
            name='ispermanent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='lastname',
            field=models.CharField(default='', max_length=70),
        ),
    ]
